src/Entity/Piment.php
<?php

namespace App\Entity;

use App\Repository\PimentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PimentRepository::class)]
class Piment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $conditions_sol = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $besoins_eau = null;

    #[ORM\Column(length: 255)]
    private ?string $periode_semi = null;

    #[ORM\Column(length: 255)]
    private ?string $periode_recolte = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $techniques_entretien = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $maladies_communes = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $astuces = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getConditionsSol(): ?string
    {
        return $this->conditions_sol;
    }

    public function setConditionsSol(string $conditions_sol): static
    {
        $this->conditions_sol = $conditions_sol;

        return $this;
    }

    public function getBesoinsEau(): ?string
    {
        return $this->besoins_eau;
    }

    public function setBesoinsEau(string $besoins_eau): static
    {
        $this->besoins_eau = $besoins_eau;

        return $this;
    }

    public function getPeriodeSemi(): ?string
    {
        return $this->periode_semi;
    }

    public function setPeriodeSemi(string $periode_semi): static
    {
        $this->periode_semi = $periode_semi;

        return $this;
    }

    public function getPeriodeRecolte(): ?string
    {
        return $this->periode_recolte;
    }

    public function setPeriodeRecolte(string $periode_recolte): static
    {
        $this->periode_recolte = $periode_recolte;

        return $this;
    }

    public function getTechniquesEntretien(): ?string
    {
        return $this->techniques_entretien;
    }

    public function setTechniquesEntretien(string $techniques_entretien): static
    {
        $this->techniques_entretien = $techniques_entretien;

        return $this;
    }

    public function getMaladiesCommunes(): ?string
    {
        return $this->maladies_communes;
    }

    public function setMaladiesCommunes(string $maladies_communes): static
    {
        $this->maladies_communes = $maladies_communes;

        return $this;
    }

    public function getAstuces(): ?string
    {
        return $this->astuces;
    }

    public function setAstuces(string $astuces): static
    {
        $this->astuces = $astuces;

        return $this;
    }
}

src/Form/PimentType.php
<?php

namespace App\Form;

use App\Entity\Piment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class PimentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class)
            ->add('description', TextareaType::class)
            ->add('conditions_sol', TextareaType::class)
            ->add('besoins_eau', TextareaType::class)
            ->add('periode_semi', TextType::class)
            ->add('periode_recolte', TextType::class)
            ->add('techniques_entretien', TextareaType::class)
            ->add('maladies_communes', TextareaType::class)
            ->add('astuces', TextareaType::class);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Piment::class,
        ]);
    }
}

src/Controller/PimentController.php
<?php

namespace App\Controller;

use App\Entity\Piment;
use App\Form\PimentType;
use App\Repository\PimentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/piment')]
final class PimentController extends AbstractController
{
    #[Route(name: 'app_piment_index', methods: ['GET'])]
    public function index(PimentRepository $pimentRepository): Response
    {
        return $this->render('piment/index.html.twig', [
            'piments' => $pimentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_piment_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $piment = new Piment();
        $form = $this->createForm(PimentType::class, $piment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($piment);
            $entityManager->flush();

            return $this->redirectToRoute('app_piment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('piment/new.html.twig', [
            'piment' => $piment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_piment_show', methods: ['GET'])]
    public function show(Piment $piment): Response
    {
        return $this->render('piment/show.html.twig', [
            'piment' => $piment,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_piment_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Piment $piment, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PimentType::class, $piment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_piment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('piment/edit.html.twig', [
            'piment' => $piment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_piment_delete', methods: ['POST'])]
    public function delete(Request $request, Piment $piment, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$piment->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($piment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_piment_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/piment/_delete_form.html.twig
<form method="post" action="{{ path('app_piment_delete', {'id': piment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ piment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/piment/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/piment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Piment{% endblock %}

{% block body %}
    <h1>Edit Piment</h1>

    {{ include('piment/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_piment_index') }}">back to list</a>

    {{ include('piment/_delete_form.html.twig') }}
{% endblock %}

templates/piment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Piment index{% endblock %}

{% block body %}
    <h1>Piment index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Description</th>
                <th>Conditions_sol</th>
                <th>Besoins_eau</th>
                <th>Periode_semi</th>
                <th>Periode_recolte</th>
                <th>Techniques_entretien</th>
                <th>Maladies_communes</th>
                <th>Astuces</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for piment in piments %}
            <tr>
                <td>{{ piment.id }}</td>
                <td>{{ piment.nom }}</td>
                <td>{{ piment.description }}</td>
                <td>{{ piment.conditionsSol }}</td>
                <td>{{ piment.besoinsEau }}</td>
                <td>{{ piment.periodeSemi }}</td>
                <td>{{ piment.periodeRecolte }}</td>
                <td>{{ piment.techniquesEntretien }}</td>
                <td>{{ piment.maladiesCommunes }}</td>
                <td>{{ piment.astuces }}</td>
                <td>
                    <a href="{{ path('app_piment_show', {'id': piment.id}) }}">show</a>
                    <a href="{{ path('app_piment_edit', {'id': piment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_piment_new') }}">Create new</a>
{% endblock %}

templates/piment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Piment{% endblock %}

{% block body %}
    <h1>Create new Piment</h1>

    {{ include('piment/_form.html.twig') }}

    <a href="{{ path('app_piment_index') }}">back to list</a>
{% endblock %}

templates/piment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Piment{% endblock %}

{% block body %}
    <h1>Piment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ piment.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ piment.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ piment.description }}</td>
            </tr>
            <tr>
                <th>Conditions_sol</th>
                <td>{{ piment.conditionsSol }}</td>
            </tr>
            <tr>
                <th>Besoins_eau</th>
                <td>{{ piment.besoinsEau }}</td>
            </tr>
            <tr>
                <th>Periode_semi</th>
                <td>{{ piment.periodeSemi }}</td>
            </tr>
            <tr>
                <th>Periode_recolte</th>
                <td>{{ piment.periodeRecolte }}</td>
            </tr>
            <tr>
                <th>Techniques_entretien</th>
                <td>{{ piment.techniquesEntretien }}</td>
            </tr>
            <tr>
                <th>Maladies_communes</th>
                <td>{{ piment.maladiesCommunes }}</td>
            </tr>
            <tr>
                <th>Astuces</th>
                <td>{{ piment.astuces }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_piment_index') }}">back to list</a>

    <a href="{{ path('app_piment_edit', {'id': piment.id}) }}">edit</a>

    {{ include('piment/_delete_form.html.twig') }}
{% endblock %}